baseURL = "http://localhost:1313/"
title = "å® ç‰©æ˜Ÿè¯­è¾…åŠ©"
canonifyURLs = true
defaultContentLanguage = "zh"
enableGitInfo = false

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"

[markup]
  [markup.highlight]
    style = "onedark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[params]
  BookTheme = "auto"
  BookSection = "*"
  BookSearch = true
  BookTranslatedOnly = false
  BookCollapseSection = false
  BookToC = true
  BookFavicon = "w.ico"
  BookEditLink = "https://github.com/atleeruy220/psh/edit/main/{{ .Path }}"

[languages]
  [languages.zh]
    languageName = "ç®€ä½“ä¸­æ–‡"
    contentDir = "content/zh"
    weight = 1
    [[languages.zh.menu.before]]
      name = "ğŸ”— é¡¹ç›®ä¸»é¡µ"
      url = "https://github.com/atleeruy220"
      weight = 10
    [[languages.zh.menu.before]]
      name = "ğŸ‘¨â€ğŸ’» ä½œè€…"
      url = "https://github.com/atleeruy220"
      weight = 20
    [[languages.zh.menu.before]]
      name = "ğŸŒŸ æèµ "
      url = "https://www.patreon.com/atleeruy220"
      weight = 30

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    [[languages.en.menu.before]]
      name = "ğŸ”— GitHub"
      url = "https://github.com/atleeruy220l"
      weight = 10
    [[languages.en.menu.before]]
      name = "ğŸ‘¨â€ğŸ’» Author"
      url = "https://github.com/atleeruy220"
      weight = 20
    [[languages.en.menu.before]]
      name = "ğŸŒŸ Donate"
      url = "https://www.patreon.com/atleeruy220"
      weight = 30